// Standalone mini vitest project for tests/capture-e2e.test.ts: a REAL, separate
// vitest run (spawned as a child process, never picked up by the repo's own outer
// `pnpm test` — see the root vitest.config.ts `exclude: tests/fixtures/**`) that
// exercises the zero-touch capture harvester end-to-end. No relation to the repo's
// own test suite; jsdom/vitest are resolved from the repo root's node_modules by
// Node's normal upward module resolution (this file lives inside the repo tree).
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    // --root is passed explicitly on the CLI invocation (see tests/capture-e2e.test.ts)
    // rather than computed here, so this file has no import.meta quirks to worry about.
    environment: "jsdom",
    globals: true,
    // Generated by capture-e2e.test.ts (captureSetup()) right before spawning —
    // not committed, so this path only resolves once the test writes it.
    setupFiles: ["./.ultra11y/capture-setup.mjs"],
    include: ["**/*.test.js"],
  },
});
