// `init` — wire ultra11y into a repo as a regression gate, so accessibility is
// enforced automatically (a git pre-commit hook and/or a CI job) and not only on
// demand. Zero dependencies (no husky): a plain POSIX `sh` hook + a GitHub Actions
// workflow, both calling `audit --changed --baseline … --fail-on …` so only NEW
// blocking non-conformities block — the existing backlog never does.
import { writeFileSync, mkdirSync, chmodSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";
import type { Severity } from "./types.js";

// English --fail-on token written into generated hooks/CI (the tool is English-first;
// parseFailOn still accepts both fr and en).
const EN_SEV: Record<Severity, string> = { bloquant: "blocking", majeur: "major", mineur: "minor" };

export function repoRoot(): string | null {
  try {
    return execFileSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return null;
  }
}

/** POSIX `sh` pre-commit hook. `enginePath` is resolved at generation time;
 *  overridable at runtime via $ULTRA11Y. Bypass once with SKIP_A11Y=1. */
export function hookScript(enginePath: string, failOn: Severity): string {
  return `#!/bin/sh
# ultra11y accessibility regression gate — generated by \`ultra11y init --hook\`.
# Blocks a commit only on NEW non-conformities >= ${EN_SEV[failOn]} in staged changes
# (vs audits/baseline.json). Bypass once with: SKIP_A11Y=1 git commit ...
[ -n "$SKIP_A11Y" ] && exit 0
ULTRA11Y=\${ULTRA11Y:-'${enginePath}'}
command -v node >/dev/null 2>&1 || { echo "ultra11y: node not found — skipping a11y gate." >&2; exit 0; }
if ! node "$ULTRA11Y" audit --changed --baseline audits/baseline.json --fail-on ${EN_SEV[failOn]}; then
  echo "ultra11y: new accessibility regression in staged changes (>= ${EN_SEV[failOn]})." >&2
  echo "  Fix it, run: node \\"$ULTRA11Y\\" fix --changed --write" >&2
  echo "  or bypass once with: SKIP_A11Y=1 git commit ..." >&2
  exit 1
fi
exit 0
`;
}

/** GitHub Actions workflow auditing the PR diff against the committed baseline. */
export function ciWorkflow(enginePath: string, failOn: Severity): string {
  return `name: a11y
# Generated by \`ultra11y init --ci\`. Fails only on NEW non-conformities >= ${EN_SEV[failOn]}
# introduced by the PR (vs audits/baseline.json) — not the existing backlog.
on:
  pull_request:
jobs:
  ultra11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: ultra11y accessibility regression gate
        run: node "${enginePath}" audit --since "origin/\${{ github.base_ref }}" --baseline audits/baseline.json --fail-on ${EN_SEV[failOn]}
`;
}

export function writeHook(root: string, enginePath: string, failOn: Severity): string {
  const dir = join(root, ".git", "hooks");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "pre-commit");
  writeFileSync(path, hookScript(enginePath, failOn));
  chmodSync(path, 0o755);
  return path;
}

export function writeCi(root: string, enginePath: string, failOn: Severity): string {
  const dir = join(root, ".github", "workflows");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "a11y.yml");
  writeFileSync(path, ciWorkflow(enginePath, failOn));
  return path;
}
